language: elixir

sudo: required

services:
  - docker

before_script:
  - docker pull couchdb:2
  - docker run -p 5984:5984 -e COUCHDB_USER=couchdb -e COUCHDB_PASSWORD=couchdb --detach --name couchdb couchdb:2

script:
  - mix coveralls.travis # This also runs the tests

elixir:
  - 1.6.4

opt_release: 20

notifications:
  email: false
